# Generated by Django 4.0.3 on 2024-02-22 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seller', '__first__'),
        ('Client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('term', models.CharField(choices=[('short', 'Short Term'), ('long', 'Long Term')], max_length=10)),
                ('job_title', models.TextField()),
                ('scope', models.CharField(choices=[('large', 'Large'), ('medium', 'Medium'), ('small', 'Small')], max_length=10)),
                ('length', models.CharField(choices=[('3-6', '3 to 6 months'), ('1-3', '1 to 3 months'), ('1', 'Less than 1 month')], max_length=5)),
                ('experience_needed', models.CharField(choices=[('entry', 'Entry'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=15)),
                ('hire_opp', models.BooleanField()),
                ('project_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('numofproposals', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.client')),
                ('freelancer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobpost.jobpost')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.seller')),
            ],
        ),
        migrations.AddField(
            model_name='jobpost',
            name='skills',
            field=models.ManyToManyField(to='jobpost.skill'),
        ),
    ]
