# Generated by Django 4.0.3 on 2024-02-22 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobpost', '0001_initial'),
        ('Seller', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cover_letter', models.TextField()),
                ('relevant_examples', models.TextField(blank=True)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='jobpost.jobpost')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.seller')),
            ],
        ),
    ]
